version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: beta
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    target-branch: beta
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    target-branch: beta
    schedule:
      interval: weekly
