version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: beta
    schedule:
      interval: weekly
    groups:
      npm-non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
      - dependency-name: "typescript"
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /
    target-branch: beta
    schedule:
      interval: weekly
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    target-branch: beta
    schedule:
      interval: weekly
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
